Repository mdflynn/refactor-tractor-fitlit, pull requests merged in 2020-10, with the labels that each got.

#1 Feature/scss
  src/css/style.scss
  src/css/variables.scss
  test/hydration-test.js
  test/userrepo-test.js
Labels: enhancement

#4 Refactor/hydration
  src/Hydration.js
  test/hydration-test.js
Labels: enhancement

#5 Clean up getFriendsNames test and method
  src/User.js
  test/user-test.js
Labels: enhancement

#8 Refactor/sleep and sleep test
  src/Sleep.js
  test/sleep-test.js
Labels: refactor

#13 Feature/refactor scripts
  package-lock.json
  package.json
  src/scripts.js
Labels: enhancement, refactor

#16 Feature/fetch api
  src/Activity.js
  src/Hydration.js
  src/scripts.js
  test/activity-test.js
  test/hydration-test.js
Labels: feature, refactor

#19 Feature/organize scss files
  src/css/mixins.scss
  src/css/style.scss
  src/css/variables.scss
  src/index.html
Labels: feature

#21 Feature/accessible html
  src/css/style.scss
  src/css/variables.scss
  src/index.html
  src/scripts.js
Labels: enhancement, feature

#24 Feature/submit button functionality
  src/api-request.js
  src/css/style.scss
  src/index.html
  src/scripts.js
Labels: enhancement, feature

#25 Refactor/get fetch
  src/api-request.js
  src/scripts.js
Labels: enhancement, feature, refactor

#26 Refactor/class inheritance
  src/Activity.js
  src/Fitness.js
  src/Hydration.js
  src/Sleep.js
  src/User-repo.js
  src/scripts.js
  test/Fitness-test.js
  test/activity-test.js
  test/hydration-test.js
  test/sleep-test.js
  test/userrepo-test.js
Labels: enhancement, feature, refactor

#28 Feature/applying chai spies
  src/Activity.js
  src/User-repo.js
  src/dom-display.js
  src/scripts.js
  test/apiRequest-test.js
  test/dom-display-test.js
  test/userrepo-test.js
Labels: enhancement, feature, refactor

#31 Feature/add readme
  README.md
Labels: enhancement, feature
